# 60분 파이토치 코스 돌파하기
해당 내용은 https://www.youtube.com/channel/UCK24Wy_G-6V-quKvVRjflgA 에서 참고하였고

추가적으로 최건호씨 깃허브 저장소에 가면 더 많은 자료를 볼 수 있음

* Tensor는 pytorch의 자료형이다.
* Tensor 변수 뒤에 .cuda()를 추가하면 GPU 연산을 할 수 있다.

* tensor type의 종류(cuda를 쓸라면 사이에 .cuda를 붙이면 된다.)
 * torch.FloatTensor => 32bit float
 * torch.DoubleTensor => 64bit floating point
 * torch.HalfTensor => 16-bit floating point
 * torch.ByteTensor => 8 bit integer (unsigned)
 * torch.CharTensor => 8 bit integer (signed) 
 * torch.ShortTensor => 16 bit integer()
 * torch.IntTensor => 32 bit integer()
 * torch.LongTensor => 64 bit integer()

In [1]:
from __future__ import print_function
import torch

# 초기화 되지 않은 Tensor를 생성할 수 있다.
매우 크게도 만들 수 있긴 함

In [2]:
x = torch.Tensor(3)
print(x)

tensor([                                   0.,
                                           0.,
        -71104899011676815060077889108049920.])


In [3]:
x = torch.empty(5, 5)
print(x)

tensor([[-6.0961e+37,  7.4549e-43,  7.0065e-44,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 1.8754e+28,  2.0110e+20,  3.3560e-06,  1.0527e-11,  2.1040e+23],
        [ 1.7376e-04,  6.6756e+22,  1.0335e-05,  2.1954e-04,  4.2000e-08],
        [ 4.0746e-11,  7.1450e+31,  4.1418e-41,  0.0000e+00,  0.0000e+00]])


In [4]:
x.shape

torch.Size([5, 5])

In [5]:
x= torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.tensor([5,5,3])
print(x)

tensor([5, 5, 3])


In [7]:
x = x.new_ones(5,5, dtype=torch.double)
print(x)
x= torch.randn_like(x, dtype =  torch.float)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)


In [8]:
print(x)

tensor([[-0.4113,  0.0103,  1.3777,  1.1836,  0.5463],
        [ 0.6821,  0.6892,  1.1443, -0.9237, -1.1009],
        [ 0.1661, -0.6771, -0.0586,  2.3049,  0.1735],
        [ 1.6848,  0.4569, -0.0793,  0.2799, -0.6442],
        [-0.4479,  0.1146, -1.1878, -0.1855,  0.5525]])


In [9]:
print(x.size())

torch.Size([5, 5])


In [10]:
#x = torch.ones(5,3, dtype=torch.double)
y = torch.rand(5,3)
#print(x + y)
print(y)

tensor([[0.9904, 0.8430, 0.9870],
        [0.2614, 0.5376, 0.7432],
        [0.1388, 0.5484, 0.6546],
        [0.9221, 0.1921, 0.4736],
        [0.7377, 0.4464, 0.5655]])


# randn(uniform distribution)

# rand(normal distribution)
평균 0이고 분산이 1이다.

In [11]:
x = torch.rand(5, 3)
print(x + y)

tensor([[1.5050, 1.4187, 1.4827],
        [0.2754, 0.6187, 1.4884],
        [1.1054, 1.1488, 0.9667],
        [1.1456, 0.4204, 0.8034],
        [1.3563, 1.0537, 1.0434]])


In [12]:
print(torch.add(x, y))

tensor([[1.5050, 1.4187, 1.4827],
        [0.2754, 0.6187, 1.4884],
        [1.1054, 1.1488, 0.9667],
        [1.1456, 0.4204, 0.8034],
        [1.3563, 1.0537, 1.0434]])


In [13]:
result = torch.empty(5,3)
torch.add(x, y, out=result) # output 텐서를 제공한다.
print(result)

tensor([[1.5050, 1.4187, 1.4827],
        [0.2754, 0.6187, 1.4884],
        [1.1054, 1.1488, 0.9667],
        [1.1456, 0.4204, 0.8034],
        [1.3563, 1.0537, 1.0434]])


In [14]:
y.add_(x)

tensor([[1.5050, 1.4187, 1.4827],
        [0.2754, 0.6187, 1.4884],
        [1.1054, 1.1488, 0.9667],
        [1.1456, 0.4204, 0.8034],
        [1.3563, 1.0537, 1.0434]])

In [15]:
print(y) # 인플레이스라 y에 저장이 된다.

tensor([[1.5050, 1.4187, 1.4827],
        [0.2754, 0.6187, 1.4884],
        [1.1054, 1.1488, 0.9667],
        [1.1456, 0.4204, 0.8034],
        [1.3563, 1.0537, 1.0434]])


In [16]:
print(y[:,1]) # 인덱싱이 가능하다. 

tensor([1.4187, 0.6187, 1.1488, 0.4204, 1.0537])


In [17]:
x = torch.randn(4,4)
y = x.view(16) # 리사이즈 된 것을 볼 수 있다. !!
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())
print(y)
print(z)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
tensor([-0.2844, -0.0112, -0.4080, -1.6139, -0.0430, -0.6373,  0.1037,  0.8274,
         0.4060, -0.9103,  0.1442, -0.2995, -1.3405,  0.8891,  0.6614, -2.4827])
tensor([[-0.2844, -0.0112, -0.4080, -1.6139, -0.0430, -0.6373,  0.1037,  0.8274],
        [ 0.4060, -0.9103,  0.1442, -0.2995, -1.3405,  0.8891,  0.6614, -2.4827]])


In [18]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.7546])
0.7545880675315857


In [19]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [20]:
b = a.numpy()
print(b) # => pytorch -> numpy로 나타낼 수 있다.

[1. 1. 1. 1. 1.]


In [21]:
a.add_(1) # add_는 인플레이스이다. 
print(a)
print(b) # 포인팅이라 이렇게 된다.

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [22]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a) # numpy를 torch로 만든다.
np.add(a, 1, out=a)

array([2., 2., 2., 2., 2.])

# Numpy 에서 Tensor로 바꾼다.

In [23]:
# numpy에서 tensor로의 변환이 쉽다
a = np.array([1,2,3,4])
b=torch.Tensor(a)

# Tensor 에서 numpy로 바꾼다
numpy() 라는 함수를 붙이자

In [24]:
a = torch.rand(3,3)
b = a.numpy()

# Tensor의 형태 변환 (view)
view라는 함수를 쓰면 형태가 변환되는 reshape을 알 수 있다.

In [25]:
a = torch.rand(3,3)
a = a.view(1,1,3,3)
a

tensor([[[[0.6270, 0.9281, 0.2541],
          [0.8286, 0.2717, 0.2023],
          [0.3507, 0.1983, 0.0743]]]])

# Tensor 합치기
.cat 이라는 함수쓰면 된다.

특정 차원에 맞게 합쳐주는데....

In [26]:
a = torch.randn(1,1,3,3)
b = torch.randn(1,1,3,3)
c = torch.cat((a,b),0)
print(c)
c = torch.cat((a,b),1)
print(c)

tensor([[[[ 1.2814, -0.7664,  1.4026],
          [ 0.3083,  2.2184,  0.3279],
          [-0.9566,  0.0263,  0.9656]]],


        [[[ 0.9020,  0.5064,  0.5653],
          [ 1.9675,  0.1251, -0.2949],
          [ 0.1006,  0.1223, -0.9616]]]])
tensor([[[[ 1.2814, -0.7664,  1.4026],
          [ 0.3083,  2.2184,  0.3279],
          [-0.9566,  0.0263,  0.9656]],

         [[ 0.9020,  0.5064,  0.5653],
          [ 1.9675,  0.1251, -0.2949],
          [ 0.1006,  0.1223, -0.9616]]]])


# Tensor 계산을 GPU로 가능

In [27]:
x = torch.randn(3,3)
y = torch.randn(3,3)
if torch.cuda.is_available():
    x=x.cuda()
    y=y.cuda()
    sum = x+y
    print(sum)

tensor([[ 0.9889, -2.5683, -0.0172],
        [ 0.4221,  0.3758, -1.3121],
        [ 0.3428,  2.4168, -1.7238]], device='cuda:0')


In [28]:
a=torch.rand(3,3)
print(a.mean())
print(a.sum())

tensor(0.4540)
tensor(4.0861)


In [29]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU

if torch.cuda.is_available():              
    device = torch.device("cuda")          # a CUDA device object 
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

tensor([[ 1.9772,  0.2928,  0.4032],
        [ 1.2558,  0.5644, -0.1179],
        [ 1.1717,  2.5108, -0.2582]], device='cuda:0')
tensor([[ 1.9772,  0.2928,  0.4032],
        [ 1.2558,  0.5644, -0.1179],
        [ 1.1717,  2.5108, -0.2582]], dtype=torch.float64)


# Autograd: Automatic Differentiation
미분을 자동으로 계산하는데 자동으로 계산하는데 사용하는 변수는
torch.autograd에 있는 Variable을 사용해야 동작이 가능해진다.
automatic differentiation 를 제공하는 기능이다.

In [30]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [31]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward>)


In [32]:
print(y.grad_fn)

# 베리어블의 선언은 이렇게 하믄 댐

autograd.Variable 은 세가지로 나뉜다. => data, grad, grad_fn

* data => Tensor 형태의 데이터가 담긴다.

* grad => 데이터가 거쳐온 레이어에 대한 미분값이 축적된다.

* grad_fn 미분 값을 계산한 함수에 대한 정보(어떤 연산에 대한 backward를 진행했다.)

# 버전이 바뀌어서 Variable을 선언하지 않아도 된다

In [33]:
# from torch.autograd import Variable

In [34]:
a = torch.rand(5)
#a = Variable(a)

In [35]:
a= torch.ones(2,2)
print(a)

tensor([[1., 1.],
        [1., 1.]])


In [36]:
a=torch.ones(2,2, requires_grad=True) 
#=> 의마하는 것은 a값이 그라디언트 값이 필요하다라는 내용
print(a)
# RNN이나 CNN에 들어가는 weight 값은 requires값이 트루라고 선언댐
# 근데 input으로 적용되는 a값은 requires_grad=True를 하지 않으면 얘가 그라디언트가
# 없는 애구나를 인식한다.

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [37]:
# 지금은 아무런 연산이 없어서 그렇다.
print("........a.data........")
print(a.data)
print("........a.grad........")
print(a.grad)
print("........a.grad_fn........")
print(a.grad_fn)

........a.data........
tensor([[1., 1.],
        [1., 1.]])
........a.grad........
None
........a.grad_fn........
None


In [38]:
b = a+2
print(b)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward>)


In [39]:
c = b**2
print(c)

tensor([[9., 9.],
        [9., 9.]], grad_fn=<PowBackward0>)


In [40]:
out=c.sum()
print(out)

tensor(36., grad_fn=<SumBackward0>)


In [41]:
# 이 out값을 토대로 backword를 진행을 해주자
#print(out)
out.backward()
# 의미가 무었이냐?
# a->b->c 를 만든다. c->out을 만든다. 그려면 
# dout/da 를 만드는데 => a.grad인데 
# 이전에 a.grad는 None이었는데 이것을 채우기 위해서 해주는 함수다
# backward()라고 보면 된다.
# 그래서 이걸 수행하면 내용을 채워준다. 

In [42]:
# 동일하게 출력을 했을 때 a.data는 그대로 있고 
# 저 grad가 채워진다. 
# grad_fn은 a가 직접적으로 수행하는 연산이 없어서 직접적으로 계산이 없다

In [43]:
# 지금은 아무런 연산이 없어서 그렇다. => grad_fn은 안참
print("........a.data........")
print(a.data)
print("........a.grad........")
print(a.grad)
print("........a.grad_fn........")
print(a.grad_fn)

........a.data........
tensor([[1., 1.],
        [1., 1.]])
........a.grad........
tensor([[6., 6.],
        [6., 6.]])
........a.grad_fn........
None


In [44]:
# 애는 그라디언트가 필요하지 않아서 None이다.
# 얘는 대신에 grad_fn이 있는데 채워진 내용 보면 addBackward 제로다.
# b가 a+2 이라 add 연산에 대한 backward를 했다.
print("........b.data........")
print(b.data)
print("........b.grad........")
print(b.grad)
print("........b.grad_fn........")
print(b.grad_fn)

........b.data........
tensor([[3., 3.],
        [3., 3.]])
........b.grad........
None
........b.grad_fn........


In [45]:
# C는 파워 연산을 해서 그렇다
# powerBackward 제로다

print("........c.data........")
print(c.data)
print("........c.grad........")
print(c.grad)
print("........c.grad_fn........")
print(c.grad_fn)

........c.data........
tensor([[9., 9.],
        [9., 9.]])
........c.grad........
None
........c.grad_fn........


In [46]:
# out은 여기다가 Sum에 대한 backward를 진행했다고 담긴다.
print("........out.data........")
print(out.data)
print("........out.grad........")
print(out.grad)
print("........out.grad_fn........")
print(out.grad_fn)

........out.data........
tensor(36.)
........out.grad........
None
........out.grad_fn........


In [47]:
# z = 3xX^2 다. 
# round x분에 round z는 6xX다. 거기다 x가 1일 때 6이지 않나 싶다.
x=torch.ones(3, requires_grad=True)
y = (x**2)
z = y*3
print(z)
grad = torch.Tensor([0.1,1,10]) 
# 그 이유는 여기다. 텐서를 벡워드 칸에 맞춰서 넣어주면
# 벡워드 되는 이 값에 곱해져서 채워지게 된다.
z.backward(grad)

tensor([3., 3., 3.], grad_fn=<MulBackward>)


In [48]:
print("........x.data........")
print(x.data)
print("........x.grad........")
print(x.grad)
print("........x.grad_fn........")
print(x.grad_fn)

........x.data........
tensor([1., 1., 1.])
........x.grad........
tensor([ 0.6000,  6.0000, 60.0000])
........x.grad_fn........
None


# torch.nn, torch.nn.functional 에 대해 알아보자

* nn 모듈에서 제공하는 기능
 * parameter, Linear, Containers, Dropout, Conv, Sparse, Pooling, Distance, Loss, Padding, Vision, Non-linear Activation, Data paralell, Normalization, Utilities
 , Recurrent
 
* nn.functional 에서 제공하는 기능들은
 * Conv, Pooling, Non-linear activation, Normalization, Linear function, Dropout, Distance, Loss, Vision 등이 있다.
 
 
## 두개가 지원하는 기능은 유사한데 사용하는 방식의 차이가 있다.

### 그러면 nn.Conv2d에 대해 알아보자
* torch.nn.Conv2d(in_channels, out_channels, kernel_size, stride=1, padding=0, dilation=1, groups=1, bias=True)
* 인풋채널, 아웃풋 채널(=> 이건 사실상 사용하는 필터의 개수)이 있다. 
* 특징은 Weight값을 직접 선언해주지 않는다. => 나온 변수를 진행하면 컨볼루션 위한 weight를 선언해준다.

### nn.functional 에 대해서 보자
* torch.nn.functional.conv2d(input, weight, bias=None, stride=1, padding=0, dilation=1, groups=1) → Tensor
* 앞서 nn.con2d에서 input 채널과 out채널을 썻던것과 달리 인풋과 weight 자체를 직접 넣어줘야 한다. 그래서 이거 쓸려면 외부에서 만든 필터를 직접 만들어서 넣어야 한다.
#### 그 외 채워주는 변수들은 같다

# 먼저 F(nn.functional)를 사용한 것

In [49]:
import torch.nn as nn
import torch.nn.functional as F # Functional를 쓰려면 Weight를 선언해야 한다.

In [73]:
input = torch.ones(1,1,7,7, requires_grad=True)
filter = torch.ones(1,1,3,3) # => 얘가 weight이다.

In [74]:
print(input)
print(filter)

tensor([[[[1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1.]]]], requires_grad=True)
tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])


In [75]:
out = F.conv2d(input, filter)
print(out) #=> 원하는 형태의 결과가 나온다.

tensor([[[[9., 9., 9., 9., 9.],
          [9., 9., 9., 9., 9.],
          [9., 9., 9., 9., 9.],
          [9., 9., 9., 9., 9.],
          [9., 9., 9., 9., 9.]]]], grad_fn=<ThnnConv2DBackward>)


In [79]:
m = nn.AdaptiveMaxPool2d((1, 1))
sp=m(out)
print(sp)

tensor([[[[9.]]]], grad_fn=<AdaptiveMaxPool2DBackward>)


In [78]:
out.backward()
print(out.grad_fn) # Backward 한다라는 것 확인

RuntimeError: grad can be implicitly created only for scalar outputs

In [54]:
print(input.grad)

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])


In [55]:
input = torch.ones(1,1,3,3, requires_grad=True)
filter = filter +1

In [56]:
out = F.conv2d(input, filter)
print(out)
out.backward()
print(out.grad_fn)

tensor([[[[18.]]]], grad_fn=<ThnnConv2DBackward>)


In [57]:
print("----input.grad-----")
print(input.grad)

----input.grad-----
tensor([[[[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]]]])


# 그 다음에 nn.Conv2d 사용한 것 
* 이러한 conv2d는 Bias 값을 가지고 있고 이 Bias 값이 추가가 되어야 저값이 나온다.

In [58]:
input = torch.ones(1,1,3,3, requires_grad=True)
func = nn.Conv2d(1,1,3)
        # 첫번째 것은 인풋채널, 두번째는 아웃풋 채널, 세번째는 커널 사이즈
        # 필터의 크기는 3x3이다. 라는 얘기다.

In [59]:
func.weight # => weight 값을 확인할 수 있다.

Parameter containing:
tensor([[[[ 0.0629, -0.2306, -0.2874],
          [ 0.2578,  0.3079,  0.1300],
          [ 0.2097, -0.1708,  0.0922]]]], requires_grad=True)

In [60]:
# 이러한 conv2d는 Bias 값을 가지고 있고 이 Bias 값이 추가가 되어야 저값이 나온다.
out = func(input)
print(func.weight.sum()) # 바이어스 넣기 전
print(func.weight.sum()+func.bias) # 바이어스가 자동으로 붙는 다는 것을 알 수 있다.
print(out)

tensor(0.3716, grad_fn=<SumBackward0>)
tensor([0.5265], grad_fn=<ThAddBackward>)
tensor([[[[0.5265]]]], grad_fn=<ThnnConv2DBackward>)


In [61]:
print(input.grad)

None


In [62]:
out.backward()
# 저기의 그라이언트는 다 1과 곱해졌기 때문에
# 1에 대한 그라디언트를 게산하면 필터 자체만 나온다.
print(input.grad)

tensor([[[[ 0.0629, -0.2306, -0.2874],
          [ 0.2578,  0.3079,  0.1300],
          [ 0.2097, -0.1708,  0.0922]]]])


# weight를 직접 설정하는 법

In [63]:
input = torch.ones(1,1,5,5, requires_grad=True)
filter = nn.Conv2d(1,1,3, bias=None)
print(filter.weight)

Parameter containing:
tensor([[[[ 0.1196, -0.1307, -0.3295],
          [-0.0057, -0.2754,  0.3155],
          [ 0.1846, -0.1475,  0.1283]]]], requires_grad=True)


In [64]:
filter.weight = torch.nn.Parameter(torch.ones(1,1,3,3) + 1) 
# 이렇게 weight 값을 직접 설정가능
# 나중에 레이어 만들거나 다른 네트워크에서 프리트레인 웨이트 넣을 때 필요

In [65]:
filter.weight

Parameter containing:
tensor([[[[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]]]], requires_grad=True)

In [66]:
out = filter(input) # => 이렇게 한건 구한 weight에다가 우리의 인풋을 넣은 것
print(out)

tensor([[[[18., 18., 18.],
          [18., 18., 18.],
          [18., 18., 18.]]]], grad_fn=<ThnnConv2DBackward>)


# ReLU, Sigmoid, tanh, Max Pooling

In [67]:
act_input = torch.randn(1,1,3,3,requires_grad=True)
print(act_input)

tensor([[[[-0.4200, -0.9965, -0.3802],
          [-0.3311,  0.3332,  1.5521],
          [-1.1324, -0.6175,  0.6984]]]], requires_grad=True)


In [68]:
act = F.relu(act_input)
print(act)

tensor([[[[0.0000, 0.0000, 0.0000],
          [0.0000, 0.3332, 1.5521],
          [0.0000, 0.0000, 0.6984]]]], grad_fn=<ReluBackward>)


In [69]:
m = nn.MaxPool2d(2, stride=1)
m_out = m(act)
print(m_out)

tensor([[[[0.3332, 1.5521],
          [0.3332, 1.5521]]]], grad_fn=<MaxPool2DWithIndicesBackward>)


In [70]:
act2 = torch.sigmoid(m_out)
print(act2)

tensor([[[[0.5825, 0.8252],
          [0.5825, 0.8252]]]], grad_fn=<SigmoidBackward>)


# Define the Network
* class 선언으로 사용하고자 하는 Network를 직접 구현할 수 있음

* class로 선언할 Network에 필수 요소는?

 * > def __init__(self):
 * > def forward(self, x): 

In [71]:
class model(nn.Module):
    def __init__(self):
        super(model, self).__init__()
        self.Max_pool = nn.MaxPool2d(2, stride=1)
        self.Avg_pool = nn.AvgPool2d(2, stride=1)
    def forward(self, x):
        x = torch.relu(x)
        x = self.Max_pool(x)
        x = torch.tanh(x)
        x = self.Avg_pool(x)
        return x

In [72]:
out = model() # 모델을 통과하고 나온 value 값으로
out(act_input) # act_input이 값이 model 안에 들어가서 
              # forward 연산을 타고 나는 결과가 보는 것과 같다.

tensor([[[[0.6177]]]], grad_fn=<AvgPool2DBackward>)