# Convolution Transposed Exercise
* torch.nn.ConvTranspose2d(in_channels, out_channels, kernel_size, stride=1, padding=0, output_padding=0, groups=1, bias=True, dilation=1)


### 1. Import Required Libraries

In [1]:
import torch
import torch.nn as nn
import torch.nn.init as init
from torch.autograd import Variable

### 2. Input Data

In [8]:
img = torch.ones((1,1,3,3),dtype=torch.float32)
print(img)

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])


### 3. Set All Weights to One

In [22]:
transpose = nn.ConvTranspose2d(in_channels=1,
                               out_channels=1,
                               kernel_size=3,
                               stride=1,
                               padding =0,
                               output_padding=0, bias=False
)

In [23]:
print(transpose.weight.data)

tensor([[[[ 0.3066, -0.3311,  0.2712],
          [-0.1765,  0.0995, -0.0123],
          [-0.0317, -0.2885, -0.0936]]]])


In [24]:
init.constant(transpose.weight.data,1) 
# 마지막 숫자가 weight의 값을 그 값으로 바꾸는 것이다.

C:\Users\gunooknam\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  """Entry point for launching an IPython kernel.


tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])

In [25]:
transpose(img)

tensor([[[[1., 2., 3., 2., 1.],
          [2., 4., 6., 4., 2.],
          [3., 6., 9., 6., 3.],
          [2., 4., 6., 4., 2.],
          [1., 2., 3., 2., 1.]]]], grad_fn=<ThnnConvTranspose2DBackward>)

## 겹치는 부분은 중첩이 된다.

### Kernel Size=3, stride=2, padding=1, output_padding=0

In [29]:
transpose = nn.ConvTranspose2d(in_channels=1, out_channels=1, kernel_size=3, stride=2, padding=1, output_padding=0, bias=False)
init.constant(transpose.weight.data,1)
transpose(img)

C:\Users\gunooknam\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  


tensor([[[[1., 2., 1., 2., 1.],
          [2., 4., 2., 4., 2.],
          [1., 2., 1., 2., 1.],
          [2., 4., 2., 4., 2.],
          [1., 2., 1., 2., 1.]]]], grad_fn=<ThnnConvTranspose2DBackward>)

### Kernel Size=3, stride=2, padding=1, output_padding=1

In [28]:
transpose = nn.ConvTranspose2d(in_channels=1, out_channels=1, kernel_size=3, stride=2, padding=1, output_padding=1, bias=False)
init.constant(transpose.weight.data,1)
transpose(img)

C:\Users\gunooknam\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  


tensor([[[[1., 2., 1., 2., 1., 1.],
          [2., 4., 2., 4., 2., 2.],
          [1., 2., 1., 2., 1., 1.],
          [2., 4., 2., 4., 2., 2.],
          [1., 2., 1., 2., 1., 1.],
          [1., 2., 1., 2., 1., 1.]]]], grad_fn=<ThnnConvTranspose2DBackward>)