# TensorFlow Dimension

In [2]:
import tensorflow as tf

sess_config = tf.ConfigProto(gpu_options=tf.GPUOptions(allow_growth=True))

# Dimension과 자주 쓰이는 Constant Value Tensors API
* Constant Value Tensors
 * tf.constant
 * tf.zeros
 * tf.zeros_like
 * tf.ones
 * tf.ones_like
 * tf.fill
* Sequences Tensors
 * tf.linspace
 * tf.range

In [9]:
# rank 0 tensor: matrix
a=tf.constant(3, name='a')
print(a)

Tensor("a_3:0", shape=(), dtype=int32)


In [16]:
# rank 1 tensor: matrix
b = tf.zeros([2])
print(b)
print(b.eval)
print(b.shape)

Tensor("zeros_7:0", shape=(2,), dtype=float32)
<bound method Tensor.eval of <tf.Tensor 'zeros_7:0' shape=(2,) dtype=float32>>
(2,)


In [7]:
# rank 2 tensor: matrix
c = tf.ones([2, 3])
print(c)

Tensor("ones:0", shape=(2, 3), dtype=float32)


In [17]:
# rank 3 tensor: 3-tensor
d = tf.fill([2, 3, 4], 3)
print(d)

Tensor("Fill:0", shape=(2, 3, 4), dtype=int32)


In [18]:
# ones_like
e = tf.ones_like(d)
print(e)

Tensor("ones_like:0", shape=(2, 3, 4), dtype=int32)


In [19]:
# linespace     1에서 5까지 4개의 점으로 나타냄
f = tf.linspace(1.0, 5.0, 4)
print(f)

Tensor("LinSpace:0", shape=(4,), dtype=float32)


In [21]:
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)
print(e.shape)
print(f.shape)

()
(2,)
(2, 3)
(2, 3, 4)
(2, 3, 4)
(4,)


In [20]:
print(a.name)
print(b.name)
print(c.name)
print(d.name)
print(e.name)
print(f.name)

a_3:0
zeros_7:0
ones:0
Fill:0
ones_like:0
LinSpace:0


# tf.Session()을 사용한 값의 출력

In [23]:
with tf.Session(config=sess_config) as sess:
  print('a:', sess.run(a), '\n')
  print('b:', sess.run(b), '\n')
  print('c:', sess.run(c), '\n')
  print('d:', sess.run(d), '\n')
  print('e:', sess.run(e), '\n')
  print('f:', sess.run(f))

a: 3 

b: [0. 0.] 

c: [[1. 1. 1.]
 [1. 1. 1.]] 

d: [[[3 3 3 3]
  [3 3 3 3]
  [3 3 3 3]]

 [[3 3 3 3]
  [3 3 3 3]
  [3 3 3 3]]] 

e: [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]] 

f: [1.        2.3333335 3.6666667 5.       ]


# tf.Session()으로 여러변수를 한방에 run

In [24]:
with tf.Session(config=sess_config) as sess:
  u, v, w, x, y, z = sess.run([a, b, c, d, e, f])
  #print(u, v, w, x, y, z)
  print('a:', u, '\n')
  print('b:', v, '\n')
  print('c:', w, '\n')
  print('d:', x, '\n')
  print('e:', y, '\n')
  print('f:', z)

a: 3 

b: [0. 0.] 

c: [[1. 1. 1.]
 [1. 1. 1.]] 

d: [[[3 3 3 3]
  [3 3 3 3]
  [3 3 3 3]]

 [[3 3 3 3]
  [3 3 3 3]
  [3 3 3 3]]] 

e: [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]] 

f: [1.        2.3333335 3.6666667 5.       ]


# 자주 쓰는 Random Tensors 들도 사용해보자
* Random Tensors
 * tf.random_normal
 * tf.truncated_normal
 * tf.random_uniform
 * tf.random_shuffle
 * tf.random_crop
 * tf.multinomial
 * tf.random_gamma
 * tf.set_random_seed

# set random number seed
 tf.set_random_seed를 통해 모든 random value generation function들이 매번 같은 값을 반환함 


In [42]:
tf.set_random_seed(219)

In [43]:
g = tf.random_normal([2, 3])
h = tf.random_uniform([2, 3, 4])

In [30]:
print(g)
print(h)
print(g.shape)
print(h.shape)
print(g.name)
print(h.name)

Tensor("random_normal:0", shape=(2, 3), dtype=float32)
Tensor("random_uniform:0", shape=(2, 3, 4), dtype=float32)
(2, 3)
(2, 3, 4)
random_normal:0
random_uniform:0


In [44]:
with tf.Session(config=sess_config) as sess:
  p, q = sess.run([g, h])
  print('g:')
  print(p, '\n')
  print('f:')
  print(q, '\n')

g:
[[-0.5474029   0.16860066 -0.19138713]
 [ 0.80937064  0.90680844  2.0031993 ]] 

f:
[[[0.49066973 0.8445177  0.625618   0.02353036]
  [0.9615165  0.6040765  0.74929976 0.04940248]
  [0.16007721 0.8590865  0.38104236 0.00932372]]

 [[0.46310246 0.6472552  0.3261279  0.5827675 ]
  [0.83381164 0.9522202  0.5972452  0.7934947 ]
  [0.03279924 0.60305345 0.6514324  0.83744   ]]] 



# 2D Tensor (matrix) 더하기 및 곱하기
* 2 x 2 random matrix 생성
 * x = [ [1, 2], [3, 4] ]
 * y = [ [5, 6], [7, 8] ]
* elementwise 더하기
* elementwise 곱하기
* matrix 곱하기


In [46]:
# TODO
x = tf.constant([ [1, 2], [3, 4] ])
y = tf.constant([ [5, 6], [7, 8] ])
# x = tf.convert_to_tensor([ [1, 2], [3, 4] ])
# y = tf.convert_to_tensor([ [5, 6], [7, 8] ])
# z: elementwise 더하기
z = x + y
# w: elementwise 곱하기
w = x * y
# v: matrix 곱하기
v = tf.matmul(x, y)

with tf.Session(config=sess_config) as sess:
  print(sess.run(x))
  print(sess.run(y))
  print(sess.run(z))
  print(sess.run(w))
  print(sess.run(v))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


# 3D Tensor 단면 자르기
 * tf.range를 이용하여 3 x 2 x 2 = 12 element list 생성
 * tf.reshape을 통해 3D Tensor 변환

In [55]:
x = tf.range(12)
x = tf.reshape(x, [3,2,2])
sess = tf.InteractiveSession(config=sess_config)
x.eval()

C:\Users\gunooknam\Anaconda3\lib\site-packages\tensorflow\python\client\session.py:1714: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

# 가장 바깥 쪽 [ 의 안쪽 부터 하나씩 시작

In [56]:
x[0,:,:].eval()

array([[0, 1],
       [2, 3]])

In [57]:
x[1,:,:].eval()

array([[4, 5],
       [6, 7]])

In [58]:
x[2,:,:].eval()

array([[ 8,  9],
       [10, 11]])

In [65]:
print( x[2,0,:].eval(), x[2,1:,0:].eval() )

[8 9] [[10 11]]
