# Constant ... 말 그대로 상수이다.

tf.constant( <br>
    value, <br>
    dtype=None, <br>
    shape=None, <br>
    name='Const', <br>
    verifiy_shape=False <br>
)

In [50]:
import tensorflow as tf
import numpy as np

sess_config = tf.ConfigProto(gpu_options=tf.GPUOptions(allow_growth=True))


In [3]:
a = tf.constant([2,2], name = 'a')
b = tf.constant([[0,1], [2,3]], name ='b')

In [6]:
x = tf.multiply(a,b,name='mul')

# Shape이 맞지 않다면 지 알아서 broadcasting을 해준다.
with tf.Session() as sess:
    print(sess.run(x))

[[0 2]
 [4 6]]


# Tensor에 특정한 값을 채우자

다음의 함수를 사용하면 shape에 맞춰서 0으로 다 채워진다.

tf.zeros(shape, dtype=tf.float32, name=None)

In [9]:
y = tf.zeros([2,3], tf.int32)
with tf.Session() as sess:
    print(sess.run(y))

[[0 0 0]
 [0 0 0]]


input tensor에 맞게 shape으로 0으로 채워진다.

tf.zeros_like(input_tensor, dtype=None, name=None, optimize=True)

In [12]:
input=tf.constant([[0,1],[2,3],[4,5]])
z = tf.zeros_like(input, tf.int32)
with tf.Session() as sess:
    print(sess.run(z))

[[0 0]
 [0 0]
 [0 0]]


# 이것들은 위와 동일한 방식 
tf.ones(shape, dtype=tf.float32, name=None)

tf.ones_like(input_tensor, dtype=None, name=None, optimize=True)



# dimension안에 값을 채운다.
tf.fill(dims, value, name=None) 


In [15]:
e=tf.fill([2, 3], 8)
with tf.Session() as sess:
    print(sess.run(e))

[[8 8 8]
 [8 8 8]]


# sequence 방식의 Constant

tf.lin_space(start, stop, 개수, name=None) => start 및 stop의 값 float32, float64 같은걸로 지정해야 한다. 그래서 0.0이렇게 '.' 을 붙임  

tf.range(start, limit=None, 간격=1, dtype=None, name='range')



In [24]:
r=tf.lin_space(0.0,10.0,4)

t=tf.range(3, 18, 2)
with tf.Session() as sess:
    t1,t2 = sess.run([r,t])
    print(t1,"\n",t2)

[ 0.         3.3333333  6.6666665 10.       ] 
 [ 3  5  7  9 11 13 15 17]


# Randomly Generated Constants
* tf.random_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None) <br>
* tf.truncated_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None) <br>
* tf.random_uniform(shape, minval=0, maxval=None, dtype=tf.float32, seed=None, name=None) <br>
* tf.random_shuffle(value, seed=None, name=None) <br>
* tf.random_crop(value, size, seed=None, name=None) <br>
* tf.multinomial(logits, num_samples, seed=None, name=None) <br>
* tf.random_gamma(shape,alpha,beta=None,dtype=tf.float32,seed=None,name=None) <br>

이러한 함수가 있다. 이것과 같이 쓰는 함수 set_random_seed(seed) 지정하는 것

In [34]:
t3=tf.random_shuffle(t)
t4=tf.random_crop(t,[1])

samples = tf.multinomial(tf.log([[0.2, 0.8]]), 10) # 다항 분포로 부터 샘플을 뽑는다.
with tf.Session() as sess:
     print(sess.run([samples,t,t4]))

[array([[1, 1, 0, 1, 0, 1, 1, 1, 1, 1]], dtype=int64), array([ 3,  5,  7,  9, 11, 13, 15, 17]), array([3])]


# Arithmetic Ops

* tf.abs
* tf.negative
* tf.sign
* tf.reciprocal
* tf.square
* tf.round
* tf.sqrt
* tf.pow
* tf.exp 등...

In [37]:
tf.int32==np.int32

True

In [38]:
tf.ones([2, 2], np.float32)

<tf.Tensor 'ones:0' shape=(2, 2) dtype=float32>

In [40]:
a = tf.zeros([2, 3], np.int32)
with tf.Session() as sess:
     a_out=sess.run(a)
     print(type(a_out)) # np의 type으로 지정하면 numpy형태로 리턴함
     

<class 'numpy.ndarray'>


# tf.Variable
 * Neural Network에서 Weight 같은 것과 같이 학습 가능한 parameter를 정의할 때와 같이 코드 실행 중에 값이 변경될 사항이 있는 경우에 쓰인다.

In [51]:
# create variables with tf.Variable
s = tf.Variable(2, name="scalar") 
m = tf.Variable([[0, 1], [2, 3]], name="matrix") 
W = tf.Variable(tf.zeros([784,10]))

with tf.Session(config=sess_config) as sess:
  writer = tf.summary.FileWriter("./graphs/05_1", sess.graph)
  writer.close()


In [56]:
tf.reset_default_graph()

In [57]:
# create variables with tf.get_variable
s = tf.get_variable("scalar", initializer=tf.constant(2)) 
m = tf.get_variable("matrix", initializer=tf.constant([[0, 1], [2, 3]]))
W = tf.get_variable("big_matrix", shape=(784, 10), initializer=tf.zeros_initializer())


In [54]:
with tf.Session(config=sess_config) as sess:
  writer = tf.summary.FileWriter("./graphs/05_2", sess.graph)
  writer.close()

In [67]:
x = s + s
y = s + m
print(x)
print(y)

Tensor("add_4:0", shape=(), dtype=int32)
Tensor("add_5:0", shape=(2, 2), dtype=int32)


# Variable을 initialize하지 않으면 에러가 난다.
* 반드시 variable을 initialize를 한 후에 sess.run을 해라

In [89]:
with tf.Session(config=sess_config) as sess:
  print(sess.run(x))
  print(sess.run(y))

FailedPreconditionError: Attempting to use uninitialized value scalar
	 [[Node: scalar/read = Identity[T=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](scalar)]]
	 [[Node: scalar/read/_1 = _HostRecv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_3_scalar/read", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op 'scalar/read', defined at:
  File "C:\Users\gunooknam\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\gunooknam\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 486, in start
    self.io_loop.start()
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 127, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\gunooknam\Anaconda3\lib\asyncio\base_events.py", line 422, in run_forever
    self._run_once()
  File "C:\Users\gunooknam\Anaconda3\lib\asyncio\base_events.py", line 1432, in _run_once
    handle._run()
  File "C:\Users\gunooknam\Anaconda3\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 117, in _handle_events
    handler_func(fileobj, events)
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\tornado\stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\tornado\stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2662, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2785, in _run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2903, in run_ast_nodes
    if self.run_code(code, result):
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-57-b505536792a8>", line 2, in <module>
    s = tf.get_variable("scalar", initializer=tf.constant(2))
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1328, in get_variable
    constraint=constraint)
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1090, in get_variable
    constraint=constraint)
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 435, in get_variable
    constraint=constraint)
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 404, in _true_getter
    use_resource=use_resource, constraint=constraint)
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 796, in _get_single_variable
    use_resource=use_resource)
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 2234, in variable
    use_resource=use_resource)
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 2224, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 2207, in default_variable_creator
    constraint=constraint)
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 259, in __init__
    constraint=constraint)
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 422, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 79, in identity
    return gen_array_ops.identity(input, name=name)
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 3887, in identity
    "Identity", input=input, name=name)
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3414, in create_op
    op_def=op_def)
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1740, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value scalar
	 [[Node: scalar/read = Identity[T=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](scalar)]]
	 [[Node: scalar/read/_1 = _HostRecv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_3_scalar/read", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]


# Initialize
* tf.global_variables_initializer()를 사용하여 모든 tf.Variable들은 한번에 초기화한다.
* 각 변수를 인자로 넣어 각각 변수별로 initialize를 할 수도 있다.



```
* DeepLearningZeroToAll 코드를 보면 아래처럼 Session 객체를 만들고 global_variables_initializer로 변수를 initialize 한다.
#initialize
sess = tf.Session()
sess.run(tf.global_variables_initializer())

# train my model
for epoch in range(training_epochs):
   ....생략....
 
```

### 전체 변수를 initialize 하는 경우

In [92]:
# The easiest way is initializing all variables at once:

init_op=tf.global_variables_initializer() # 전역으로 모든 변수를 initialize 한다.

with tf.Session(config=sess_config) as sess:
    sess.run(init_op)
    print(sess.run(x))
    print(sess.run(y))


4
[[2 3]
 [4 5]]


### 특정 변수를 지정해서 intialize 하는 경우

In [88]:
# Initialize only a subset of variables:

a = tf.Variable(2, name="scalara") 
b = tf.Variable(5, name="scalarb") 
c = tf.Variable(7, name="scalarc")
with tf.Session(config=sess_config) as sess:
    sess.run(tf.variables_initializer([a, b])) #initial 한 것만 sess.run 가능
    print(sess.run(a))
    print(a.eval()) # sess.run(a) 과 동일한 느낌
    print(sess.run(b))
    #print(sess.run(c)) # a, b는 initialize가 되어있고, c는 되어있지 않아 에러가 난다
    
    

2
2
5


### single의 변수만 initialize 하는 경우

In [82]:
#Initialize a single variable

W = tf.Variable(tf.truncated_normal([700, 10]))
with tf.Session() as sess:
    sess.run(W.initializer)
    print(W.eval())
    print(W.eval().shape)

[[ 0.32362074 -1.3716617  -1.1283426  ... -0.16868484  1.2561421
   1.4809089 ]
 [ 1.2609833  -0.4201352  -0.44806734 ... -1.1594571   0.0947558
  -0.02227844]
 [ 0.6300272   0.7646711   0.25516662 ...  0.18187617  0.33080822
  -1.1465149 ]
 ...
 [ 0.66365224 -0.49407226  0.5691589  ... -1.1611903   0.26602998
   0.08850358]
 [ 0.22575833  0.6935829  -0.26533628 ... -0.43410602  1.3511854
   0.6446917 ]
 [ 0.34823537 -1.695422   -1.9334395  ...  1.2527173   1.3045478
  -1.0332865 ]]
(700, 10)


## 아래 코드의 답은 10이 나온다.
* W.assign(100) 이라는 것은 assign op라는 operation을 정의한다. 이것은 유효한 세션에서 발동한다. 이것을 지정해야 실행이 된다.

In [93]:
W = tf.Variable(10)
W.assign(100)
with tf.Session() as sess:
    sess.run(W.initializer)
    print(W.eval()) 

10


### 아래처럼 W.assign 값을 할당 받아서 그것을 sess.run을 할동시키면
### 그러한 W의 intialize가 할당된다.

In [94]:
W = tf.Variable(10)
assign_op = W.assign(100)
with tf.Session() as sess:
    sess.run(W.initializer)
    sess.run(assign_op)
    print(W.eval()) 

100


* assign은 즉 연산을 정의하는 것이다. 내가 with 문 도중에 특정연산을 하고 싶을 때 sess.run(assign으로 할당한 객체)를 넣고 사용한다.

In [95]:
# create a variable whose original value is 2
my_var = tf.Variable(2, name="my_var") 

# assign a * 2 to a and call that op a_times_two
my_var_times_two = my_var.assign(2 * my_var)

with tf.Session() as sess:
    sess.run(my_var.initializer)
    sess.run(my_var_times_two)
    print(my_var.eval())
    sess.run(my_var_times_two)
    print(my_var.eval())

4
8


## assign_add, assign_sub로 assign 가능

In [100]:
my_var = tf.Variable(10)

with tf.Session() as sess:
    sess.run(my_var.initializer) # increment by 10
    sess.run(my_var.assign_add(10)) # >> 20 # decrement by 2 
    print(my_var.eval())
    sess.run(my_var.assign_sub(2)) # >> 18
    print(my_var.eval())


20
18


## Session을 따로 객체에 할당하여 사용할 수 있다.

In [102]:
W = tf.Variable(10)

sess1 = tf.Session()
sess2 = tf.Session()

sess1.run(W.initializer)
sess2.run(W.initializer)

print(sess1.run(W.assign_add(10))) # >> 20
print(sess2.run(W.assign_sub(2))) # >> 8

print(sess1.run(W.assign_add(100))) # >> 120
print(sess2.run(W.assign_sub(50))) # >> -42

sess1.close()
sess2.close()

20
8
120
-42


In [5]:
import tensorflow as tf
with tf.device('/gpu:0'):
    a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
    b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
    c = tf.matmul(a, b)
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
print(sess.run(c))

InvalidArgumentError: Cannot assign a device for operation 'MatMul_1': Operation was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0 ]. Make sure the device specification refers to a valid device.
	 [[Node: MatMul_1 = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/device:GPU:0"](a_1, b_1)]]

Caused by op 'MatMul_1', defined at:
  File "C:\Users\gunooknam\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\gunooknam\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 486, in start
    self.io_loop.start()
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 127, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\gunooknam\Anaconda3\lib\asyncio\base_events.py", line 422, in run_forever
    self._run_once()
  File "C:\Users\gunooknam\Anaconda3\lib\asyncio\base_events.py", line 1432, in _run_once
    handle._run()
  File "C:\Users\gunooknam\Anaconda3\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 117, in _handle_events
    handler_func(fileobj, events)
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\tornado\stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\tornado\stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2662, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2785, in _run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2903, in run_ast_nodes
    if self.run_code(code, result):
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-87c1767f4aa0>", line 5, in <module>
    c = tf.matmul(a, b)
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\tensorflow\python\ops\math_ops.py", line 2014, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 4567, in mat_mul
    name=name)
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3414, in create_op
    op_def=op_def)
  File "C:\Users\gunooknam\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1740, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Cannot assign a device for operation 'MatMul_1': Operation was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0 ]. Make sure the device specification refers to a valid device.
	 [[Node: MatMul_1 = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/device:GPU:0"](a_1, b_1)]]
