# 가끔씩 쓸만한 Numpy의 잡기술과 애매한 것들 모음
* 생각나는 대로 계속 계속 추가할 예정

* Accuracy 구할 때 
 * 데이터 셋의 True값과 내가 구한 예측값의 정확도를 측정하려고 한다.

In [1]:
import numpy as np

In [20]:
# True Label 값
Y= np.array([0,
             1,
             3,
             0,
             1,
             2])

# 나의 Model로 인한 예측치
Y_Pred = [[1,0,0,0],
          [1,0,0,0],
          [0,0,0,1],
          [1,0,0,0],
          [0,1,0,0],
          [0,0,1,0]]

Y_Pred_argmax = np.argmax( Y_Pred, axis=1)

print(Y)
print(Y_Pred_argmax)

# 1.
print("accuracy is ", np.mean(Y==Y_Pred_argmax))

# 2.
print("accuracy is ", np.sum(Y==Y_Pred_argmax)/Y.shape[0])

[0 1 3 0 1 2]
[0 0 3 0 1 2]
accuracy is  0.8333333333333334
accuracy is  0.8333333333333334


* Axis에 대해서... axis는 축이다.
* 이 부분은 numpy 다룰 때 매우 헷갈리는 부분 중의 하나임

In [60]:
tmp_1d=np.array([1,2,3,4])
tmp_1d.shape
tmp_1d.ndim # 몇 차원 배열인지 알려준다.

1

In [61]:
c=np.sum(tmp_1d) 
c

10

## sum과 같은 연산을 해버리면 기본적으로 차원이 날라간다.
1차원만 연산하면 상관이 없는데 2차, 3차, 4차원 연산을 할 때 어떻게 연산을 할 것인가에 대해 정의해줄 수 있다.

그래서 axis라는 인자를 넣어줘서 연산에 대한 방향을 정한다.

In [57]:
tmp_2d=np.array([[1,2,3,4],
                 [4,5,6,7],
                 [6,7,8,9]])
tmp_2d.ndim

2

In [62]:
np.sum(tmp_2d,axis=1) # axis를 1로 해줬는데 가장 안쪽 [ ]의 값이 다 더해지고 차원 하나가 날라갔다.

array([10, 22, 30])

In [30]:
np.sum(tmp_2d,axis=0) # 마찬자기로 차원하나는 날라갔다. 하지만 연산이 이뤄진 방향은 다르다. axis가 0이어서 '[' 한개를 건너띔

array([11, 14, 17, 20])

## 가장 안쪽 [ ]의 합을 구하려면 ndim을 구하고 ndim-1의 axis로 연산을 해야한다.

In [42]:
tmp_3d=np.array([ [ [1, 2],
                    [4, 5],
                    [6, 7] ]
                 ,
                  [ [3, 4],
                    [5, 6],
                    [7, 8] ]
                 ,
                  [ [5, 6],
                    [7, 8],
                    [9, 9] ] ] )
tmp_3d.shape

(3, 3, 2)

In [52]:
np.sum(tmp_3d,axis=2) # x방향

array([[ 3,  9, 13],
       [ 7, 11, 15],
       [11, 15, 18]])

In [55]:
tmp_3d.ndim

3

In [53]:
np.sum(tmp_3d,axis=1) # y 방향

array([[11, 14],
       [15, 18],
       [21, 23]])

In [63]:
np.sum(tmp_3d,axis=0) # [ 를 2개를 건너뛰어서 연산한다. z 방향

array([[ 9, 12],
       [16, 19],
       [22, 24]])

## Shape 다듬기

data의 모양을 원하는 대로 만드는 것은 매우 중요하다. 이미지는 (width,height,channel) 이러한 포맷으로 들어있는 경우가 많다.

혹은 (channel, width, height) 이러한 포맷으로 들어있는 경우도 많았다. 

이러한 data의 배열은 (N개 , width*height*channel) 이러한 식으로 reshape이 되어 layer에 인풋으로 들어가는 경우가 많다.

( List 자체는 numpy와 다르게 shape을 못씀 가끔 실수하는 경우 있음. )

In [100]:
X = np.random.rand(32,32,3)

## 1D matrix로 쭉 피기

In [101]:
X_1D = X.reshape(1,-1)
print(X_1D.shape)

(1, 3072)


In [102]:
N = 100 # 데이터 셋이 100개라면

Total = []

for i in range(N):
   Total.append(X_1D)

print("X_input을 배열로 만든다면 길이 : " ,len(Total))

result = X_1D
for i in range(N-1):
   result=np.vstack((result,X_1D)) 
# vertical로 쌓임 horizontal로 쌓으면 [ ]안으로 다 값이 넣어진다.
    
print("X_input을 numpy객체로 만든다면 : " ,result.shape)

X_input을 배열로 만든다면 길이 :  100
X_input을 numpy객체로 만든다면 :  (100, 3072)


## 비슷한 함수로 concatenate도 있다.
이걸 쓰려면 대신 axis를 항상 생각을 해줘야함....

In [123]:
a = np.array([[1,5,9],[2,6,10]])
b = np.array([[3,7,11],[4,8,12]])

c = np.concatenate((a,b),axis=0)
d = np.concatenate((a,b),axis=1)
print("c is : \n",c)
print("--------------------")
print("d is : \n",d)

c is : 
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
--------------------
d is : 
 [[ 1  5  9  3  7 11]
 [ 2  6 10  4  8 12]]


## Numpy에서 Transpose 할 때 

기본적으로 numpy객체.T해서 transpose 가능 그런데 원하는 모형으로 tranpose 하려면 

객체.transpose(2,1,0) 과 같이 0,1,2 순을 원하는 순서로 바꾸면 된다.


In [113]:
X2 = np.random.rand(3,32,32)

X2_trans = X2.transpose(2,1,0)

print(X2_trans.shape) # 이런식으로 shape을 바꿀 수도 있다.
print(X2_trans.T.shape)

(32, 32, 3)
(3, 32, 32)
